mattermost:
  user:
    name: StravaBot
    icon-url: https://strava-mattermost-connector.herokuapp.com/img/user_icon.png

strava:
  subscription.id: ${SUBSCRIPTION_ID}
  subscription:
    verify-token: ${VERIFY_TOKEN}
    callback-url: https://strava-mattermost-connector.herokuapp.com/strava/event
    subscribe-on-start-up: true

connector:
  base-url: https://strava-mattermost-connector.herokuapp.com
  approval-url: https://strava-mattermost-connector.herokuapp.com/registration/finalize
  encryption-key: ${ENCRYPTION_KEY}

spring:
  redis:
    host-name: ${REDIS_HOST_NAME}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}}
  security:
    oauth2:
      client:
        registration:
          strava:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: activity:read_all
            authorization-uri: https://www.strava.com/oauth/authorize
            token-uri: https://www.strava.com/oauth/token
            redirect-uri: https://strava-mattermost-connector.herokuapp.com/login/oauth2/code/strava

google:
  api-key: ${GOOGLE_API_KEY}
  static-maps:
    url: https://maps.googleapis.com/maps/api/staticmap